remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
title: Website Research Docs
description: Detailed technical and operational research notes for government digital initiatives.
google_analytics: "G-QEF40ZXSEK"